version: '3.7'
services:
  app:
    build:
      context: .docker
      dockerfile: app.devenv
    depends_on:
      - db
    command: [ "sleep", "infinity" ]
  db:
    image: "mysql:8.0"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
